version: 2.1
workflows:
  main:
    jobs:
      - shell-tests:
          filters:
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - install-python:
          filters:
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          matrix:
            parameters:
              python-version:
                - 2.7.18
                - 3.5.10
                - 3.6.13
                - 3.7.10
                - 3.8.10
                - 3.9.4
                - 3.9.5
              ubuntu-version:
                - "20.04"
                - "18.04"
          requires:
            - shell-tests
      - release:
          requires:
            - install-python
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          context: main
orbs:
  bats: circleci/bats@1.0
  gh: circleci/github-cli@1.0
commands:
  install-pungi-deps:
    steps:
      - run:
          name: "Install Pungi Dependencies"
          command: |
            sudo apt-get update && sudo apt-get install -y \
              build-essential \
              curl \
              make \
              libbz2-dev \
              libffi-dev \
              liblzma-dev \
              libncursesw5-dev \
              libreadline-dev \
              libssl-dev \
              libsqlite3-dev \
              libxml2-dev \
              libxmlsec1-dev \
              llvm \
              tk-dev \
              wget \
              xz-utils \
              zlib1g-dev
  setup-pungi:
    steps:
      - run:
          name: "Setup Pungi"
          command: |
            echo 'export PUNGI_ROOT="$HOME/project"' >> $BASH_ENV
            echo 'export PATH="$PUNGI_ROOT/shims:$PUNGI_ROOT/bin:$PATH"' >> $BASH_ENV
      - run: pungi --version

jobs:
  shell-tests:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - install-pungi-deps
      - bats/install
      - run:
          name: "Run Bats Tests"
          command: bats test
  install-python:
    parameters:
      python-version:
        type: string
      ubuntu-version:
        type: string
    docker:
      - image: cimg/base:2021.07-<< parameters.ubuntu-version >>
    steps:
      - checkout
      - install-pungi-deps
      - setup-pungi
      - run:
          name: "Install & Set & Python version"
          command: |
            if [[ "<< parameters.python-version >>" == "3.9.5" ]];then
              DIRECT="--direct"
              echo "Installing Python using the --direct flag"
            fi
            pungi install $DIRECT << parameters.python-version >>
            pungi global << parameters.python-version >>
      - run:
          name: "Test Python version"
          command: python --version 2>&1 | grep "<< parameters.python-version >>"
      - run:
          name: "Showcase what we have"
          command: |
            pungi version
            python --version
            python -m pip --version
      - when:
          condition:
            matches:
              pattern: "^3"
              value: << parameters.python-version >>
          steps:
            - run:
                name: "Test version of Python"
                command: python3 --version | grep << parameters.python-version >>
      - when:
          condition:
            matches:
              pattern: "^2"
              value: << parameters.python-version >>
          steps:
            - run:
                name: "Test version of Python"
                command: python --version | grep << parameters.python-version >>
  release:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - gh/setup
      - run:
          name: "Create a release on GitHub"
          command: gh release create $CIRCLE_TAG --title="Pungi $CIRCLE_TAG"
