#!/usr/bin/env bash
# Usage: pungi version-file-write <file> <version>

set -e
[ -n "$PUNGI_DEBUG" ] && set -x

PUNGI_VERSION_FILE="$1"
shift || true
versions=("$@")

if [ -z "$versions" ] || [ -z "$PUNGI_VERSION_FILE" ]; then
  pungi-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
pungi-prefix "${versions[@]}" >/dev/null

# Write the version out to disk.
# Create an empty file. Using "rm" might cause a permission error.
> "$PUNGI_VERSION_FILE"
for version in "${versions[@]}"; do
  echo "$version" >> "$PUNGI_VERSION_FILE"
done
