#!/usr/bin/env bash
# Usage: pungi version-file [<dir>]
# Summary: Detect the file that sets the current pungi version
set -e
[ -n "$PUNGI_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -f "${root}/.python-version" ]; then
      echo "${root}/.python-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$PUNGI_DIR" || {
    [ "$PUNGI_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${PUNGI_ROOT}/version"
fi
