#!/usr/bin/env bash
# Summary: Show the current Python version(s) and its origin
#
# Shows the currently selected Python version(s) and how it was
# selected. To obtain only the version string, use `pungi
# version-name'.

set -e
[ -n "$PUNGI_DEBUG" ] && set -x

exitcode=0
OLDIFS="$IFS"
IFS=: PUNGI_VERSION_NAMES=($(pungi-version-name)) || exitcode=$?
IFS="$OLDIFS"

for PUNGI_VERSION_NAME in "${PUNGI_VERSION_NAMES[@]}"; do
  echo "$PUNGI_VERSION_NAME (set by $(pungi-version-origin))"
done

exit $exitcode
